# vim: set fdm=indent:
nameOverride: ""
fullnameOverride: ""

replicaCount: 1

namespace: "flink-connectors"
commonLabels:
  system.processing: "true"
  release: monitoring
  app: flink


# repository: sunbirded.azurecr.io/data-pipeline
#   tag: "release-5.2.0_RC1_2c615f8_12"
# docker pull sunbirded.azurecr.io/sunbird-datapipeline:release-4.9.0_RC4_1
registry: sanketikahub
repository: flink-connectors
tag: 1.17.2-scala_2.12-java11
imagePullSecrets: []
imagePullPolicy: IfNotPresent

## Databases
global:
  redis:
    host: redis-denorm.redis.svc.cluster.local
    port: 6379
  cassandra:
    host: localhost
    port: 9042
  kafka:
    host: "kafka-headless.kafka.svc.cluster.local"
    port: 9092
  zookeeper:
    host: "zookeeper-headless.kafka.svc.cluster.local"
    port: 2181
  image:
    registry: ""

podAnnotations: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 9999
  fsGroup: 0

securityContext:
  {}
  # readOnlyRootFilesystem: false
  # capabilities:
  #   drop:
  #   - ALL

service:
  type: ClusterIP
  ports:
    - name: http
      port: 8081
      targetPort: 8081

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - /

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80

nodeSelector: {}
tolerations: []
affinity: {}

configmap:
  enabled: false
  mountPath: /config

serviceAccount:
  create: true
  name: ""

# Example values.yaml structure
initContainers:
  {}
  # - name: init-myservice
  #   image: busybox:1.28
  #   command: ['sh', '-c', "until nslookup kubernetes.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for myservice; sleep 2; done"]

sidecars:
  {}
  # - name: log-reader # Sidecar container
  #   image: busybox # Use another busybox image
  #   command: ["/bin/sh"] # Override the default command
  #   args: ["-c", "tail -f /var/log/app.log"] # Run a shell script that tails the log file

opa:
  enabled: false

jobmanager:
  rpc_port: 6123
  blob_port: 6124
  query_port: 6125
  ui_port: 8081
  prom_port: 9250
  heap_memory: 1024

rest_port: 80
resttcp_port: 8081

taskmanager:
  prom_port: 9251
  rpc_port: 6122
  heap_memory: 1024
  replicas: 1
  cpu_requests: 0.3

checkpoint_store_type: null

# AWS S3 Details
s3_auth_type: "serviceAccount"
s3_access_key: ""
s3_secret_key: ""
s3_endpoint: ""
s3_path_style_access: ""

# Azure Container Details
azure_account: "azure-test"
azure_secret: "azure-secret"

# Azure Container Details
cloud_storage_flink_bucketname: flink-state-backend
cloud_storage_content_bucketname: sunbird-content-dev
cert_container_name: dev-e-credentials
# cloud_storage_endpoint: https://{{ .Values.global.azure_storage_account_name }}.blob.core.windows.net

postgres:
  max_connections: 2
  sslmode: false
  db_name: analytics
  db_port: 5432

checkpointing:
  enabled: false
  statebackend: null

log4j_console_properties: |
  # This affects logging for both user code and Flink
  rootLogger.level = INFO
  rootLogger.appenderRef.console.ref = ConsoleAppender
  rootLogger.appenderRef.rolling.ref = RollingFileAppender

  # Uncomment this if you want to _only_ change Flink's logging
  logger.flink.name = org.apache.flink
  logger.flink.level = INFO

  # The following lines keep the log level of common libraries/connectors on
  # log level INFO. The root logger does not override this. You have to manually
  # change the log levels here.
  logger.akka.name = akka
  logger.akka.level = ERROR
  logger.kafka.name= org.apache.kafka
  logger.kafka.level = ERROR
  logger.hadoop.name = org.apache.hadoop
  logger.hadoop.level = ERROR
  logger.zookeeper.name = org.apache.zookeeper
  logger.zookeeper.level = ERROR

  # Log all infos to the console
  appender.console.name = ConsoleAppender
  appender.console.type = CONSOLE
  appender.console.layout.type = PatternLayout
  appender.console.layout.pattern = %d{yyyy-MM-dd HH:mm:ss,SSS} %-5p %-60c %x - %m%n

  # Log all infos in the given rolling file
  appender.rolling.name = RollingFileAppender
  appender.rolling.type = RollingFile
  appender.rolling.append = false
  appender.rolling.fileName = ${sys:log.file}
  appender.rolling.filePattern = ${sys:log.file}.%i
  appender.rolling.layout.type = PatternLayout
  appender.rolling.layout.pattern = %d{yyyy-MM-dd HH:mm:ss,SSS} %-5p %-60c %x - %m%n
  appender.rolling.policies.type = Policies
  appender.rolling.policies.size.type = SizeBasedTriggeringPolicy
  appender.rolling.policies.size.size=10MB
  appender.rolling.strategy.type = DefaultRolloverStrategy
  appender.rolling.strategy.max = 5

  # Suppress the irrelevant (wrong) warnings from the Netty channel handler
  logger.netty.name = org.apache.flink.shaded.akka.org.jboss.netty.channel.DefaultChannelPipeline
  logger.netty.level = OFF

flink_resources:
  taskmanager:
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 1
        memory: 1024Mi
  jobmanager:
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 1
        memory: 1024Mi

serviceMonitor:
  jobmanager:
    enabled: true
    interval: 30s
    scrapeTimeout: 10s
    labels: {} # additional labels e.g. release: prometheus
    honorLabels: true
    jobLabel: "app.kubernetes.io/name"
    port: prom
  taskmanager:
    enabled: true
    interval: 30s
    scrapeTimeout: 10s
    labels: {} # additional labels e.g. release: prometheus
    honorLabels: true
    jobLabel: "app.kubernetes.io/name"
    port: prom


# override flink_jobs
# flink_jobs:


commonAnnotations:
  reloader.stakater.com/auto: "true"